version: '2'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=event
    ports:
      - "5432:5432"
    restart: always
  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: pgadmin4_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@event.test.pl
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    restart: always